### ISSUE TITLE
buck demo failed to load libjni.so

### ISSUE THREAD

**Issue by RimingChen** [facebook/buck#1401]
hi,
   I followed steps on [https://buckbuild.com/setup/getting_started.html](url), but get error when running the android demo apk: 
Process: com.facebook.buck.demo, PID: 7377
                                                 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.facebook.buck.demo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.facebook.buck.demo-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjni.so"

then I add modify the .buckconfig in the cxx section like:

cxxflags = -g -std=c++11 -Wall -I /Users/chenriming/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm/usr/include \
  -I /Users/chenriming/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm/usr/include/android

still get no libjni.so but libjni.a in the gen dir.
can someone help me out?

**Comment by styurin** [comment]
Are you using the latest buck version? This was fixed in https://github.com/facebook/buck/issues/1176.

**Comment by RimingChen** [comment]
I'm using the release version installed by home-brew on Mac:

cross-platform-scale-2015-demo$ buck --version
buck version v2017.05.31.01

Also I've tried your tips on [#1176](https://github.com/facebook/buck/issues/1176)
$ buck kill && rm -rf buck-out
$ buck build demo_app_android

still the same problem.

**Comment by RimingChen** [comment]
thanks buddy, i checkout the latest code from [buck](https://github.com/facebook/buck.git), it works, the shared lib finally comes out!
One question, the ndk-version we set in the ndk section will not work if we set it to its short name when using new ndk version?
e.g..
 the following setting reports "No native platforms detected.":
ndk_version = r14b
but   ndk_version = 14.1.3816874
works.

**Comment by styurin** [comment]
This is because NDK versions are stored differently depending on the version: https://github.com/facebook/buck/blob/93e2aafe9c8031f2b086a589e53bbc068dcf0bf1/src/com/facebook/buck/android/DefaultAndroidDirectoryResolver.java#L43-L46

I'll update the docs.

**Comment by styurin** [comment]
updated docs in 6640d076ab97c4b1e4a906b6e2dca9ca7d7f2e35
